# Generated by Django 3.1.4 on 2021-02-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripplerock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('reason', models.TextField()),
                ('life_quality', models.TextField()),
                ('amenities', models.TextField()),
                ('ideal_free_time', models.TextField()),
                ('noncontentment', models.TextField()),
                ('want_to_learn', models.TextField()),
            ],
        ),
    ]
