# Generated by Django 3.1.4 on 2021-02-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripplerock', '0004_auto_20210225_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='age',
            field=models.IntegerField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='amenities',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='ideal_free_time',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='life_quality',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='noncontentment',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='reason',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='time_on_island',
            field=models.CharField(blank=True, default='0 - 1', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='want_to_learn',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
