# Generated by Django 3.1.4 on 2021-02-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripplerock', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(blank=True, default=' ', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
