# Generated by Django 3.1.4 on 2021-02-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripplerock', '0007_auto_20210226_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='type',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
