# Generated by Django 3.1.4 on 2021-02-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ripplerock', '0008_paragraph_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='type',
            new_name='page',
        ),
    ]
